CLASS zbp_r_online_shop_sc03 DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF
zr_online_shop_sc03.
  PUBLIC SECTION.
    CLASS-DATA cv_pr_mapped TYPE RESPONSE FOR MAPPED i_purchaserequisitiontp.
ENDCLASS.
CLASS zbp_r_online_shop_sc03 IMPLEMENTATION.
ENDCLASS.
